### ISSUE TITLE
Server cipher algorithm (option cipher) dropdown box empty

### ISSUE THREAD

**Issue by bradgass** [a-schild/webmin-openvpn-debian-jessie#1]
I am having a problem with the OpenVPN Webmin module (3.0) not giving any options (blank) to select the cipher for the server in the dropdown box.

This issue may have been around for a long time and I simply didn't notice it until my upgrade from OpenVPN 2.3.2 to OpenVPN 2.4.3.

I believe this may be related to a change in the output of "openvpn --show-ciphers" starting with OpenVPN 2.3.12 on 23-Aug-2016 (reference https://github.com/openvpn/openvpn/commit/610fdbbd).

**Comment by katak-nyulink** [comment]
Cannot open this module in new version webmin 1.870

**Comment by Big44** [comment]
@katak-nyulink same here, I just get a red bar across the top of the page and nothing else happens. Are there any logs we can check to try and get a better idea of what is actually going?

**Comment by 68b32** [comment]
Did you try the latest version of the official webmin module from http://www.webmin.com/cgi-bin/search_third.cgi?search=openvpn ? Most changes done here were merged into the official version.

**Comment by Big44** [comment]
@68b32 Yes, I tried that first and it gave me the same result, When trying to access the openvpn module from the servers list it just shows a loading bar across the top of the page and nothing happens no matter how long I leave it. Same with this version, I was hoping this was the fix.

**Comment by 68b32** [comment]
I could reproduce this behavior. I think it is a problem with the "Authentic Theme". Changing the theme to "Old Webmin Theme" will make the module page accessible again. I raised an issue here https://github.com/webmin/webmin/issues/762

**Comment by aliasdoc** [comment]
With the last official version (http://www.webmin.com/cgi-bin/search_third.cgi?search=openvpn), I have the same problem cipher algorithm dropdown is empty.

**Comment by aliasdoc** [comment]
Hi @68b32 , is there any solution ??
Thank you.
